replicaCount: 1

image:
  repository: registry.minter.network/minter-contest-bot
  pullPolicy: Always

imagePullSecrets:
  - name: registry.minter.network

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

service:
  port: 80

ingress:
  domain: minter-contest-bot.kubernetes.icu
  tls:
    secret: "wildcard"
  servicename: static

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
